### ISSUE TITLE
__repr__

### ISSUE THREAD

**Issue by sjanssen2** [biocore/calour#12]
I am creating a new Experiment: `calour.experiment.Experiment(file_biom, file_metadata)` in a notebook and get the following error. I guess it's only because there is no representation for this class. But it might scare the user.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/sjanssen/miniconda3/envs/notebookServer/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    670                 type_pprinters=self.type_printers,
    671                 deferred_pprinters=self.deferred_printers)
--> 672             printer.pretty(obj)
    673             printer.flush()
    674             return stream.getvalue()

/home/sjanssen/miniconda3/envs/notebookServer/lib/python3.5/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    381                             if callable(meth):
    382                                 return meth(obj, self, cycle)
--> 383             return _default_pprint(obj, self, cycle)
    384         finally:
    385             self.end_group()

/home/sjanssen/miniconda3/envs/notebookServer/lib/python3.5/site-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    502         # A user-provided repr. Find newlines and replace them with p.break_()
--> 503         _repr_pprint(obj, p, cycle)
    504         return
    505     p.begin_group(1, '<')

/home/sjanssen/miniconda3/envs/notebookServer/lib/python3.5/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    699     """A pprint that just redirects to the normal repr function."""
    700     # Find newlines and replace them with p.break_()
--> 701     output = repr(obj)
    702     for idx,output_line in enumerate(output.splitlines()):
    703         if idx:

TypeError: __repr__ returned non-string (type NoneType)`

**Comment by RNAer** [comment]
fixed
