### ISSUE TITLE
pandas concatenation sorting depracation warning

### ISSUE THREAD

**Issue by amnona** [biocore/calour#179]
./Users/amnon/git/calour/calour/training.py:130: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  new.feature_metadata = pd.concat([pd.DataFrame(index=vec.get_feature_names()), new.feature_metadata])
./Users/amnon/git/calour/calour/training.py:130: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  new.feature_metadata = pd.concat([pd.DataFrame(index=vec.get_feature_names()), new.feature_metadata])

**Comment by RNAer** [comment]
we don't wanna sort, right?

**Comment by RNAer** [comment]
closed via #185
