### ISSUE TITLE
plot() got multiple values for keyword argument 'feature_field'

### ISSUE THREAD

**Issue by sjanssen2** [biocore/calour#18]
I pulled the latest sources from calour, dbbact 10 minutes ago.

`e.plot(gui='jupyter', cmap='jet', feature_field='id')` works fine.
However, if I want to use plot_sort() like
`e.plot_sort(field, gui='jupyter', cmap='jet', feature_field='id')`
it raises the following problem:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-b62491552467> in <module>()
     12         print(e.sample_metadata.shape, e.feature_metadata.shape, e.data.shape)
     13 #         print(e.feature_metadata.columns)
---> 14         e.plot_sort(field, gui='jupyter', cmap='jet', feature_field='id')
     15         break
     16     break

/home/sjanssen/miniconda3/envs/calour/src/calour/calour/amplicon_experiment.py in plot_sort(exp, field, **kwargs)
    225             newexp.plot(feature_field='taxonomy', **kwargs)
    226         else:
--> 227             newexp.plot(sample_field=field, feature_field='taxonomy', **kwargs)

TypeError: plot() got multiple values for keyword argument 'feature_field'

**Comment by RNAer** [comment]
fixed
