### ISSUE TITLE
future warning from sklearn

### ISSUE THREAD

**Issue by amnona** [biocore/calour#180]
test_rep_sorted_strtified (test_training.RTests) ... /home/travis/miniconda/envs/calour/lib/python3.6/site-packages/sklearn/utils/validation.py:71: FutureWarning: Pass n_repeats=2, random_state=None as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)

**Comment by Casebash** [comment]
I just ran into this as well

**Comment by yishairasowsky** [comment]
@Casebash @RNAer @amnona @gregcaporaso @ElDeveloper what is the answer?

**Comment by RNAer** [comment]
This should be an easy fix. I am trying to reproduce the warning to see which lines of code trigger it, but can't. any ideas?

![image](https://user-images.githubusercontent.com/1000056/125926816-013c311d-ec11-4fa8-ba84-c393cb93f527.png)
