### ISSUE TITLE
diff abundance

### ISSUE THREAD

**Issue by sjanssen2** [biocore/calour#20]
I am running `ediff = e.diff_abundance(field, 'low', 'high', fdr_method='dsfdr')`
and get the following error. I guess it is because there are no diff. abundant features and the function returns None instead of an empty experiment.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-71-41c409f21385> in <module>()
     14         e.cluster_data(axis=0, inplace=True)
     15         print(e.sample_metadata.shape, e.feature_metadata.shape, e.data.shape)
---> 16         ediff = e.diff_abundance(field, 'low', 'high') #, fdr_method='dsfdr')
     17 #         if ediff is not None:
     18 #             print(ediff.feature_metadata.shape, e.feature_metadata.shape)

/home/sjanssen/miniconda3/envs/calour/src/calour/calour/util.py in inner(*args, **kwargs)
     57         v = param.get('axis', None)
     58         if v is None:
---> 59             return func(*args, **kwargs)
     60         if isinstance(v, str):
     61             param['axis'] = conversion[v.lower()]

/home/sjanssen/miniconda3/envs/calour/src/calour/calour/experiment.py in inner(*args, **kwargs)
    169             log = exp._log
    170             try:
--> 171                 new_exp = func(*args, **kwargs)
    172                 if exp._log is True:
    173                     param = ['%r' % i for i in args[1:]] + ['%s=%r' % (k, v) for k, v in kwargs.items()]

/home/sjanssen/miniconda3/envs/calour/src/calour/calour/analysis.py in diff_abundance(exp, field, val1, val2, method, transform, numperm, alpha, fdr_method)
    163     keep, odif, pvals = dsfdr.dsfdr(data, labels, method=method, transform_type=transform, alpha=alpha, numperm=numperm, fdr_method=fdr_method)
    164     logger.info('method %s. number of higher in %s : %d. number of higher in %s : %d. total %d' % (method, val1, np.sum(odif[keep] > 0), val2, np.sum(odif[keep] < 0), np.sum(keep)))
--> 165     return _new_experiment_from_pvals(exp, keep, odif, pvals)
    166 
    167 

/home/sjanssen/miniconda3/envs/calour/src/calour/calour/experiment.py in inner(*args, **kwargs)
    173                     param = ['%r' % i for i in args[1:]] + ['%s=%r' % (k, v) for k, v in kwargs.items()]
    174                     param = ', '.join(param)
--> 175                     new_exp._call_history.append('{0}({1})'.format(fn, param))
    176                     exp._log = False
    177             finally:

AttributeError: 'NoneType' object has no attribute '_call_history'

**Comment by RNAer** [comment]
should be fixed
