### ISSUE TITLE
Struggling to Figure Out The Structure of Biom File

### ISSUE THREAD

**Issue by hlee885** [biocore/calour#287]
Hi, 

I have been following the [dbbact calour](http://redirect.viglink.com/?key=71fe2139a887ad501313cd8cce3053c5&subId=7332523&u=http%3A//biocore.github.io/calour/notebooks/microbiome_step_by_step.html%23Import-the-calour-module) tutorial and having hard time to figure out the structure of biom format.
In the website, it is using biom file and text file both to load the data.

```
dat=ca.read_amplicon('data/chronic-fatigue-syndrome.biom',
                     'data/chronic-fatigue-syndrome.sample.txt',
                     normalize=10000,min_reads=1000)
```

I was wondering if I can have some help in terms of the structure of .biom format in this tutorial.
I hope to hear from any of you soon.

Thank you,
-Jin

**Comment by amnona** [comment]
Dear Jin,
please see response (and continue the discussion) [here](https://dbbact.boards.net/thread/6/struggling-figure-structure-biom-file?page=1&scrollTo=7) in the [dbbact forum](https://dbbact.boards.net/).
