### ISSUE TITLE
Expose the fontsize in highlights

### ISSUE THREAD

**Issue by mortonjt** [biocore/calour#54]
Would be nice to expose the fontsize in [_ax_color_bar](https://github.com/biocore/calour/blob/master/calour/heatmap/heatmap.py#L255)

Specifically, that would need to be passed into this [line](https://github.com/biocore/calour/blob/master/calour/heatmap/heatmap.py#L315) and the heights will need to be modified.

**Comment by RNAer** [comment]
fixed together with ticket #56
